package:
  name: node
  version: 4.2.1

build:
  number: 0

requirements:
  build:
    - gcc
    - libc-musl
    - python

test:
  commands:
    - node -e "console.log('Hello from node.js ' + process.version)"

source:
  fn: node-v4.2.1.tar.gz
  url: https://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz
  sha256: 8861b9f4c3b4db380fcda19a710c0430c3d62d03ee176c64db63eef95a672663

about:
  home: https://nodejs.org
  license: MIT

