#!/bin/bash

# Resource: http://serverfault.com/questions/425132/controlling-tomcat-with-supervisor

shutdown() {
    date
    echo "Shutting down Tomcat"
    unset CATALINA_PID # Necessary in some cases
    $CATALINA_HOME/bin/catalina.sh stop
}

startup() {
    date
    echo "Starting Tomcat"
    export JAVA_HOME=$(readlink -f $PREFIX/bin/java | sed "s:/bin/java::")
    export JAVA_HOME="/usr/lib/jvm/java-7-oracle"
    export CATALINA_HOME="/usr/share/tomcat6"
    export CATALINA_BASE="/opt/tomcat6-instance"
    export CATALINA_PID=/tmp/$$    

    . $CATALINA_HOME/bin/catalina.sh start

    # Allow any signal which would kill a process to stop Tomcat
    trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP
     
    echo "Waiting for $(cat $CATALINA_PID)"
    wait $(cat $CATALINA_PID)
}

startup
