package:
  name: jq
  version: 1.5.0

build:
  number: 0

requirements:
  build:
    - ruby


source:
  fn: jq-1.5.tar.gz
  url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz
  sha256: c4d2bfec6436341113419debf479d833692cc5cdab7eb0326b5a4d4fbe9f493c

test:
  commands:
    - jq --version
    - jq --help

about:
  home: https://github.com/stedolan/jq
  license: ¯\_(ツ)_/¯
