package:
  name: bats
  version: 0.4.0

build:
  number: 0

source:
  git_rev: v0.4.0
  git_url: https://github.com/sstephenson/bats.git

test:
  commands:
    - bats --help

about:
  home: https://github.com/sstephenson/bats
  license: MIT
