package:
  name: ruby
  version: 2.2.3

build:
  number: 0

source:
  fn: ruby-2.2.3.tar.gz
  url: https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.gz
  sha256: df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce

test:
  commands:
    - ruby --version
    - ruby -e 'require "rubygems"'
    - gem --version

requirements:
  build:
    - jemalloc
    - openssl
    - readline
    - yaml
    - zlib
  run:
    - jemalloc
    - openssl
    - readline
    - yaml
    - zlib

about:
  home: https://www.ruby-lang.org/
  license: BSD

