package:
  name: nginx
  version: 1.9.15

source:
  fn: nginx-1.9.15.tar.gz
  url: http://nginx.org/download/nginx-1.9.15.tar.gz
  sha256: cc89b277cc03f403c0b746d60aa5943cdecf59ae48278f8cb7e2df0cbdb6dac3

build:
  number: 0
  no_link: etc/*
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc
    - openssl 1.0.2*
    - pcre
    - zlib
  run:
    - openssl 1.0.2*
    - pcre
    - zlib

test:
  commands:
    - nginx -V

about:
  home: http://www.nginx.org
  license: 2-clause BSD-like license

