package:
  name: nginx
  version: 1.9.10

source:
  fn: nginx-1.9.10.tar.gz
  url: http://nginx.org/download/nginx-1.9.10.tar.gz
  sha256: fb14d76844cab0a5a0880768be28965e74f9956790f618c454ef6098e26631d9
  patches:
    - configure.patch

build:
  number: 1
  no_link: etc/*
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc
    - openssl
    - pcre
    - zlib
  run:
    - openssl
    - pcre
    - zlib

test:
  commands:
    - nginx -V

about:
  home: http://www.nginx.org
  license: 2-clause BSD-like license

