package:
  name: mongodb
  version: 2.6.11

build:
  number: 0

requirements:
  build:
    - gcc >=4.8.2
    - scons
    - python 2.7*
    - scons
    - openssl
    - pip
  run:
    - openssl

test:
  commands:
    - mongod --version

source:
  fn: mongodb-src-r2.6.11.tar.gz
  url: https://fastdl.mongodb.org/src/mongodb-src-r2.6.11.tar.gz
  sha256: e1a64a1ef7114f3e8ed3c7acaa4e97ffe30e2b57a1a5f2a40f0018bad3b8d12f

about:
  home: https://www.mongodb.org/
  license: AGPL
