package:
  name: fluentd
  version: 0.12.14

build:
  number: 0

requirements:
  build:
    - ruby 2.2.3
    - jemalloc
  run:
    - ruby 2.2.3
    - jemalloc

test:
  commands:
    - |
      export LD_PRELOAD=$PREFIX/lib/libjemalloc.so
      fluentd --setup ./fluent
      fluentd -c ./fluent/fluent.conf -vv &
      sleep 5
      echo '{"json":"message"}' | fluent-cat debug.test

