package:
  name: fluentd
  version: 0.12.17

build:
  number: 0

requirements:
  build:
    - ruby >=2.2.3
  run:
    - ruby >=2.2.3

test:
  commands:
    - |
      fluentd --setup ./fluent
      fluentd -c ./fluent/fluent.conf -vv > test_output.log &
      sleep 5
      echo '{"json":"very unique message"}' | fluent-cat debug.test
      grep "very unique message" test_output.log
      kill %1
      wait
