{% set buildnum = 3 %}

package:
  name: ansible
  version: 2.0.0.2

build:
  number: {{ buildnum + 5 }}    [osx]
  number: {{ buildnum }}    [linux]

source:
  fn: 'Ansible-2.0.0.2#{ extra_var }.tar.gz'
  url: https://pypi.python.org/packages/source/a/ansible/ansible-2.0.0.2.tar.gz
  md5: 816d0c49e084383e47a725c761a0e413 

requirements:
  build:
    - python
    - paramiko
    - jinja2
    - pyyaml
    - setuptools
    - pycrypto >=2.6
    - six
  run:
    - python
    - paramiko
    - jinja2
    - pyyaml
    - setuptools
    - pycrypto >=2.6
    - six

test:
  commands:
    - python -c 'import ansible'

about:
  home: https://github.com/ansible/ansible
  license: GPLv3

