--- Makefile
+++ Makefile
@@ -45,6 +45,11 @@
 # limit.
 #

+PREFIX_PYTHON=$(PREFIX)
+ANT=ant
+JCC=$(PYTHON) -m jcc --shared
+NUM_FILES=8
+
 # Mac OS X 10.6 (64-bit Python 2.6, Java 1.6)
 #PREFIX_PYTHON=/usr
 #ANT=ant
 